runtime: python39  # Specifies Python 3.9 runtime (use python38 or python310 if necessary)

entrypoint: streamlit run app.py --server.port=8080 --server.address=0.0.0.0  # Command to run the Streamlit app

env_variables:
  STREAMLIT_SERVER_PORT: 8080  # Configures Streamlit to use port 8080
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"  # Allow access from all IPs

handlers:
  # Serve static files (like images, CSS) from the 'static/' directory (if you have one)
  - url: /static
    static_dir: static/

  # Route all other URLs to your Streamlit app
  - url: /.* 
    script: auto

# You can add additional configurations here as needed
